stages:
  - lint
  - unittest
  - functest
  - build

image: python:2.7-alpine


flake8:
  stage: lint
  script:
    - pip install flake8
    - flake8 setup.py src/

unittest_py27:
  stage: unittest
  script:
    - pip install -q -r requirements-test.txt
    - pip install -q -e .
    - py.test -m "not with_network"

functest:
  stage: functest
  script:
    - pip install -q -r requirements-test.txt
    - pip install -q -e .
    - py.test -m with_network

sdist:
  stage: build
  only:
    - tags
  script:
    - python setup.py sdist
  artifacts:
    when: on_success
    name: "ver-$CI_COMMIT_TAG"
    paths:
      - sdist/idcfcloud-dns-$CI_COMMIT_TAG.tar.gz
