stages:
  - lint
  - unittest
  - functest
  - build

image: python:2.7-alpine


flake8:
  stage: lint
  script:
    - pip install flake8
    - flake8 setup.py src/

unittest_py27:
  stage: unittest
  script:
    - pip install -q -r requirements-test.txt
    - pip install -q -e .
    - py.test

functest:
  stage: functest
  only:
    - master
    - tags
  script:
    - pip install -q -r requirements-test.txt
    - pip install -q -e .
    - py.test -m functest

sdist:
  stage: build
  only:
    - tags
  script:
    - python setup.py sdist
  artifacts:
    when: on_success
    name: "idcfcloud-dns-$CI_COMMIT_TAG_packages"
    paths:
      - dist/idcfcloud-dns-$CI_COMMIT_TAG.tar.gz
